#!/bin/sh
set -o errexit 

NOTEBOOK=initial_analysis

cp ../h/${NOTEBOOK}.ipynb tmp${NOTEBOOK}.ipynb

jupyter nbconvert --execute --ExecutePreprocessor.timeout=-1 --to notebook --stdout tmp_${NOTEBOOK}.ipynb > ${NOTEBOOK}.ipynb

jupyter nbconvert --to html ${NOTEBOOK}.ipynb

jupyter nbconvert --to pdf ${NOTEBOOK}.ipynb

rm -f tmp_${NOTEBOOK}.ipynb